/*
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = EdFi.OdsApi.Sdk.Client.OpenAPIDateConverter;

namespace EdFi.OdsApi.Sdk.Models.All
{
    /// <summary>
    /// SampleStudentEducationOrganizationAssociationAddressSchoolDistrict
    /// </summary>
    [DataContract(Name = "sample_studentEducationOrganizationAssociationAddressSchoolDistrict")]
    public partial class SampleStudentEducationOrganizationAssociationAddressSchoolDistrict : IEquatable<SampleStudentEducationOrganizationAssociationAddressSchoolDistrict>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SampleStudentEducationOrganizationAssociationAddressSchoolDistrict" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SampleStudentEducationOrganizationAssociationAddressSchoolDistrict() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SampleStudentEducationOrganizationAssociationAddressSchoolDistrict" /> class.
        /// </summary>
        /// <param name="schoolDistrict">The school district in which the address is located. (required).</param>
        public SampleStudentEducationOrganizationAssociationAddressSchoolDistrict(string schoolDistrict = default(string))
        {
            // to ensure "schoolDistrict" is required (not null)
            if (schoolDistrict == null)
            {
                throw new ArgumentNullException("schoolDistrict is a required property for SampleStudentEducationOrganizationAssociationAddressSchoolDistrict and cannot be null");
            }
            this.SchoolDistrict = schoolDistrict;
        }

        /// <summary>
        /// The school district in which the address is located.
        /// </summary>
        /// <value>The school district in which the address is located.</value>
        [DataMember(Name = "schoolDistrict", IsRequired = true, EmitDefaultValue = true)]
        public string SchoolDistrict { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SampleStudentEducationOrganizationAssociationAddressSchoolDistrict {\n");
            sb.Append("  SchoolDistrict: ").Append(SchoolDistrict).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SampleStudentEducationOrganizationAssociationAddressSchoolDistrict);
        }

        /// <summary>
        /// Returns true if SampleStudentEducationOrganizationAssociationAddressSchoolDistrict instances are equal
        /// </summary>
        /// <param name="input">Instance of SampleStudentEducationOrganizationAssociationAddressSchoolDistrict to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SampleStudentEducationOrganizationAssociationAddressSchoolDistrict input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.SchoolDistrict == input.SchoolDistrict ||
                    (this.SchoolDistrict != null &&
                    this.SchoolDistrict.Equals(input.SchoolDistrict))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SchoolDistrict != null)
                {
                    hashCode = (hashCode * 59) + this.SchoolDistrict.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // SchoolDistrict (string) maxLength
            if (this.SchoolDistrict != null && this.SchoolDistrict.Length > 250)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for SchoolDistrict, length must be less than 250.", new [] { "SchoolDistrict" });
            }

            yield break;
        }
    }

}
