/*
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = EdFi.OdsApi.Sdk.Client.OpenAPIDateConverter;

namespace EdFi.OdsApi.Sdk.Models.All
{
    /// <summary>
    /// TrackedChangesTpdmCandidateKey
    /// </summary>
    [DataContract(Name = "trackedChanges_tpdm_candidateKey")]
    public partial class TrackedChangesTpdmCandidateKey : IEquatable<TrackedChangesTpdmCandidateKey>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TrackedChangesTpdmCandidateKey" /> class.
        /// </summary>
        /// <param name="candidateIdentifier">A unique alphanumeric code assigned to a candidate..</param>
        public TrackedChangesTpdmCandidateKey(string candidateIdentifier = default(string))
        {
            this.CandidateIdentifier = candidateIdentifier;
        }

        /// <summary>
        /// A unique alphanumeric code assigned to a candidate.
        /// </summary>
        /// <value>A unique alphanumeric code assigned to a candidate.</value>
        [DataMember(Name = "candidateIdentifier", EmitDefaultValue = false)]
        public string CandidateIdentifier { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TrackedChangesTpdmCandidateKey {\n");
            sb.Append("  CandidateIdentifier: ").Append(CandidateIdentifier).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TrackedChangesTpdmCandidateKey);
        }

        /// <summary>
        /// Returns true if TrackedChangesTpdmCandidateKey instances are equal
        /// </summary>
        /// <param name="input">Instance of TrackedChangesTpdmCandidateKey to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TrackedChangesTpdmCandidateKey input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.CandidateIdentifier == input.CandidateIdentifier ||
                    (this.CandidateIdentifier != null &&
                    this.CandidateIdentifier.Equals(input.CandidateIdentifier))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CandidateIdentifier != null)
                {
                    hashCode = (hashCode * 59) + this.CandidateIdentifier.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // CandidateIdentifier (string) maxLength
            if (this.CandidateIdentifier != null && this.CandidateIdentifier.Length > 32)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CandidateIdentifier, length must be less than 32.", new [] { "CandidateIdentifier" });
            }

            // CandidateIdentifier (string) minLength
            if (this.CandidateIdentifier != null && this.CandidateIdentifier.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CandidateIdentifier, length must be greater than 1.", new [] { "CandidateIdentifier" });
            }

            yield break;
        }
    }

}
